# Makefile for Davinci_HD related audio files
obj-$(CONFIG_SOUND_DAVINCI_HD) += davinci-audio-oss.o
obj-$(CONFIG_SOUND_DAVINCI_TLV320AIC32) += davinci-audio-aic32.o

davinci-audio-oss-objs := davinci-audio-dma-intfc.o evm_audio_info.o audio_controller.o