#
# Makefile for common code for Toshiba TX4939 based systems
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#

obj-y	+= setup.o irq.o led.o
obj-$(CONFIG_PROC_FS) += proc.o

