#
# Makefile for the NEC Electronics Corporation VR5701 SolutionGearII specific kernel interface routines
# under Linux.
#

obj-y += setup.o irq.o int-handler.o irq_vr5701.o 
EXTRA_AFLAGS: = $(CFLAGS)
