#
# Makefile for the touchscreen input drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_BITSY)	+= h3600_ts_input.o
obj-$(CONFIG_TOUCHSCREEN_GUNZE)	+= gunze.o
obj-$(CONFIG_TOUCHSCREEN_OMAP)	+= omap/
obj-$(CONFIG_TOUCHSCREEN_MHN)   += ts_mhn.o
