#
# sound/pci/vr5701/Makefile
#
# Makefile for ALSA
#
# Author: Sergey Podstavin <spodstavin@ru.mvista.com>
#
# 2005 (c) MontaVista Software, Inc. This file is licensed under
# the terms of the GNU General Public License version 2. This program
# is licensed "as is" without any warranty of any kind, whether express
# or implied.
#

snd-nec_vr5701_sg2-objs := nec_vr5701_sg2.o

obj-$(CONFIG_SND_VR5701) += snd-nec_vr5701_sg2.o
