#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by arch/xtensa/Makefile
 *
 */

#define PT_PC 0 /* offsetof (struct pt_regs, pc) */
#define PT_PS 4 /* offsetof (struct pt_regs, ps) */
#define PT_DEPC 8 /* offsetof (struct pt_regs, depc) */
#define PT_EXCCAUSE 12 /* offsetof (struct pt_regs, exccause) */
#define PT_EXCVADDR 16 /* offsetof (struct pt_regs, excvaddr) */
#define PT_DEBUGCAUSE 20 /* offsetof (struct pt_regs, debugcause) */
#define PT_WMASK 24 /* offsetof (struct pt_regs, wmask) */
#define PT_LBEG 28 /* offsetof (struct pt_regs, lbeg) */
#define PT_LEND 32 /* offsetof (struct pt_regs, lend) */
#define PT_LCOUNT 36 /* offsetof (struct pt_regs, lcount) */
#define PT_SAR 40 /* offsetof (struct pt_regs, sar) */
#define PT_ICOUNTLEVEL 56 /* offsetof (struct pt_regs, icountlevel) */
#define PT_SYSCALL 52 /* offsetof (struct pt_regs, syscall) */
#define PT_AREG 64 /* offsetof (struct pt_regs, areg[0]) */
#define PT_AREG0 64 /* offsetof (struct pt_regs, areg[0]) */
#define PT_AREG1 68 /* offsetof (struct pt_regs, areg[1]) */
#define PT_AREG2 72 /* offsetof (struct pt_regs, areg[2]) */
#define PT_AREG3 76 /* offsetof (struct pt_regs, areg[3]) */
#define PT_AREG4 80 /* offsetof (struct pt_regs, areg[4]) */
#define PT_AREG5 84 /* offsetof (struct pt_regs, areg[5]) */
#define PT_AREG6 88 /* offsetof (struct pt_regs, areg[6]) */
#define PT_AREG7 92 /* offsetof (struct pt_regs, areg[7]) */
#define PT_AREG8 96 /* offsetof (struct pt_regs, areg[8]) */
#define PT_AREG9 100 /* offsetof (struct pt_regs, areg[9]) */
#define PT_AREG10 104 /* offsetof (struct pt_regs, areg[10]) */
#define PT_AREG11 108 /* offsetof (struct pt_regs, areg[11]) */
#define PT_AREG12 112 /* offsetof (struct pt_regs, areg[12]) */
#define PT_AREG13 116 /* offsetof (struct pt_regs, areg[13]) */
#define PT_AREG14 120 /* offsetof (struct pt_regs, areg[14]) */
#define PT_AREG15 124 /* offsetof (struct pt_regs, areg[15]) */
#define PT_WINDOWBASE 44 /* offsetof (struct pt_regs, windowbase) */
#define PT_WINDOWSTART 48 /* offsetof(struct pt_regs, windowstart) */
#define PT_SIZE 128 /* sizeof(struct pt_regs) */
#define PT_AREG_END 192 /* offsetof (struct pt_regs, areg[XCHAL_NUM_AREGS]) */
#define PT_USER_SIZE 192 /* offsetof(struct pt_regs, areg[XCHAL_NUM_AREGS]) */

#define TASK_PTRACE 16 /* offsetof (struct task_struct, ptrace) */
#define TASK_MM 108 /* offsetof (struct task_struct, mm) */
#define TASK_ACTIVE_MM 112 /* offsetof (struct task_struct, active_mm) */
#define TASK_PID 144 /* offsetof (struct task_struct, pid) */
#define TASK_THREAD 464 /* offsetof (struct task_struct, thread) */
#define TASK_THREAD_INFO 4 /* offsetof (struct task_struct, thread_info) */
#define TASK_STRUCT_SIZE 656 /* sizeof (struct task_struct) */

#define THREAD_RA 464 /* offsetof (struct task_struct, thread.ra) */
#define THREAD_SP 468 /* offsetof (struct task_struct, thread.sp) */
#define THREAD_CP_SAVE 512 /* offsetof (struct task_struct, thread.cp_save) */
#define THREAD_CURRENT_DS 472 /* offsetof (struct task_struct, thread.current_ds) */

#define MM_USERS 32 /* offsetof(struct mm_struct, mm_users) */
#define MM_PGD 28 /* offsetof (struct mm_struct, pgd) */
#define MM_CONTEXT 324 /* offsetof (struct mm_struct, context) */

#define PT_SINGLESTEP_BIT 31 /* PT_SINGLESTEP_BIT */

#define _CLONE_VM 256 /* CLONE_VM */
#define _CLONE_UNTRACED 8388608 /* CLONE_UNTRACED */

#endif
