obj-$(CONFIG_BLK_DEV_IDE_SWARM)		+= swarm.o
obj-$(CONFIG_BLK_DEV_IDE_TX4939)	+= ide-tx4939.o
obj-$(CONFIG_BLK_DEV_IDE_TX4938)	+= ide-tx4938.o
obj-$(CONFIG_BLK_DEV_IDE_AU1XXX)	+= au1xxx-ide.o
obj-$(CONFIG_BLK_DEV_IDE_PHOENIX)	+= phoenix_ide.o

EXTRA_CFLAGS	:= -I../
