#
# Makefile for the video capture/playback device drivers.
#

obj-$(CONFIG_PXA_CAMERA_ZL)  += pxa_camera_zl.o camera.o ci.o \
				ov2620.o ov2620_hw.o ov2630.o ov2630_hw.o \
				ov7660.o ov7660_hw.o
