#
# Makefile for the linux ppc-specific parts of QE UCC
#
obj-$(CONFIG_UCC)	+= ucc.o
obj-$(CONFIG_UCC_SLOW)	+= ucc_slow.o
obj-$(CONFIG_UCC_FAST)	+= ucc_fast.o ucc_slow.o
obj-$(CONFIG_UCC_GETH)	+= ucc_geth.o ucc_geth_phy.o
